--- #YAML:1.0
name: HTTPD-ADS
version: 0.5
license: gpl
distribution_type: module
requires:
  CGI::Carp: 1.26
  CLASS: 0.91
  Class::Accessor: 0.18
  Class::Constructor: 1.0.0
  Class::DBI: 0.94
  Class::DBI::AbstractSearch: 0.03
  Class::DBI::Pg: 0.03
  Compress::Zlib: 1.22
  Date::Calc: 5.3
  HTTPD::Log::Filter: 1.07
  IO::Socket::UNIX: 1.20
  IO::Zlib: 1.01
  IPC::Cmd: 0.04
  Net::IP::Route::Reject: 0.3
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Class::Constructor:
    file: lib/Class/Constructor.pm
    version: 1.1.0
  HTTPD::ADS:
    file: lib/HTTPD/ADS.pm
    version: 0.5
  HTTPD::ADS::AbuseNotify:
    file: lib/HTTPD/ADS/AbuseNotify.pm
    version: 0.1
  HTTPD::ADS::Blacklist:
    file: lib/HTTPD/ADS/DBI.pm
    version: 0.2
  HTTPD::ADS::Blocker:
    file: lib/HTTPD/ADS/Blocker.pm
    version: 0.1
  HTTPD::ADS::DBI:
    file: lib/HTTPD/ADS/DBI.pm
    version: 0.2
  HTTPD::ADS::Eventrecords:
    file: lib/HTTPD/ADS/DBI.pm
    version: 0.2
  HTTPD::ADS::Hosts:
    file: lib/HTTPD/ADS/DBI.pm
    version: 0.2
  HTTPD::ADS::OpenProxyDetector:
    file: lib/HTTPD/ADS/OpenProxyDetector.pm
    version: 0.2
  HTTPD::ADS::Request_strings:
    file: lib/HTTPD/ADS/DBI.pm
    version: 0.2
  HTTPD::ADS::Times:
    file: lib/HTTPD/ADS/Times.pm
    version: 0.1
  HTTPD::ADS::Usernames:
    file: lib/HTTPD/ADS/DBI.pm
    version: 0.2
  HTTPD::ADS::Whitelist:
    file: lib/HTTPD/ADS/DBI.pm
    version: 0.2
  HTTPD::ADS::notice_templates:
    file: lib/HTTPD/ADS/DBI.pm
    version: 0.2
  HTTPD::ADS::notified:
    file: lib/HTTPD/ADS/DBI.pm
    version: 0.2
  HTTPD::ADS::proxy_tested:
    file: lib/HTTPD/ADS/DBI.pm
    version: 0.2
generated_by: Module::Build version 0.21
